server: 
  port: 3309
  servlet: 
    context-path: /pinmaonews
spring: 
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/pinmao?serverTimezone=UTC
    username: root 
    password: 123456
    driver: com.mysql.jdbc.Driver